name: Weather ETL every 30 mins

on:
  schedule:
    - cron: '*/30 * * * *'  # Every 30 minutes
  workflow_dispatch:

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gspread oauth2client requests pandas

    - name: Set Google Credentials from Base64
      run: |
        echo "${{ secrets.SERVICE_ACCOUNT_B64 }}" | base64 --decode > service_account.json
        echo "Service account file created successfully"

    - name: Set OpenWeather API Key
      run: echo "OPENWEATHER_API_KEY=${{ secrets.OPENWEATHER_API_KEY }}" >> $GITHUB_ENV

    - name: Run ETL Script
      run: python weather_etl_openweathermap.py
