name: Weather ETL to Google Sheets

on:
  schedule:
    - cron: '0 0,12 * * *'  # Runs at 00:00 UTC and 12:00 UTC every day
  workflow_dispatch:        # Manual trigger if needed

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread oauth2client requests pandas

      - name: Set Google Credentials from Base64
        run: |
          echo "${{ secrets.SERVICE_ACCOUNT_B64 }}" | base64 --decode > service_account.json
          echo "Service account file created successfully"

      - name: Run ETL Script
        run: python weather_etl.py
        env: 
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}

